inital test for putter

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -1,41 +1,84 @@
 # This workflow will build a .NET project
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
 
-name: Sample Run and Dependabot Auto-merge
+name: Sample Run Tests and Dependabot
 on:
   push:
     branches: [ master ]
+  pull_request_target:
+    branches: [ master ]
+    types: [opened, synchronize, reopened, unlabeled]
 
-permissions:
-  id-token: write
-  contents: write
-  pull-requests: write
-  statuses: write
+concurrency:
+  group: dotnet.yml
+  cancel-in-progress: false
 
 jobs:
+  # Evaluates if the sample tests should run. If the workflow is triggered by a push OR
+  # is triggered by a pull request without the 'skip-sample-tests' label, the sample tests should run.
+  # Otherwise, the sample tests will be skipped
+  check-if-should-run:
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'skip-sample-tests')) }}
+    outputs:
+      should_run: 'true'
+      is_fork: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork }}
+    steps:
+      - run: echo "Evaluating workflow conditions"
+
+  # Workflow will pause and wait here if it is triggered by a fork PR. The workflow will continue to wait until
+  # an approved member of the environment 'manual_approval' allows the workflow to run
+  wait-for-approval:
+    needs: [ check-if-should-run ]
+    if: ${{ needs.check-if-should-run.outputs.is_fork == 'true' }}
+    runs-on: ubuntu-latest
+    environment: manual-approval
+    steps:
+      - run: echo "Fork PR approved by a team member."
+
+  # Sample run tests of the KCL
+  # Runs only if (check-if-should-run allows AND (the PR is not from a fork OR it has been approved to run))
   sample-run:
-    timeout-minutes: 9
+    needs: [ check-if-should-run, wait-for-approval ]
+    permissions:
+      id-token: write
+    if: ${{ always() && needs.check-if-should-run.outputs.should_run == 'true' && (needs.check-if-should-run.outputs.is_fork != 'true' || needs.wait-for-approval.result == 'success') }}
+    timeout-minutes: 20
     runs-on: ${{ matrix.os }}
     defaults:
       run:
         shell: bash
 
+    # Initialize matrix based on PR labels (more-tests label runs more tests)
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        python-version: ${{ github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'more-tests') && fromJSON('["3.9", "3.11"]') || fromJSON('["3.9"]') }}
+#        jdk-version: ${{ github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'more-tests') && fromJSON('["8", "11", "17", "21", "24"]') || fromJSON('["8", "11"]') }}
+#        os: [ ubuntu-latest, macOS-latest, windows-latest ]
+
+    # Initialize matrix based on PR labels (more-tests label runs more tests)
     strategy:
       fail-fast: false
       matrix:
-        jdk-version: [ "8", "11", "17", "21", "24" ]
+        node-version: [ "6.0.x" ]
+        jdk-version: [ "8" ]
         os: [ ubuntu-latest, macOS-latest, windows-latest ]
 
     steps:
-      - name: Checkout working directory
+      # For pull_request_target, checkout PR head instead of merge commit
+      - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
 
+      # Configure AWS Credentials. Role session name is unique to avoid OIDC errors when running multiple tests concurrently
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-region: us-east-1
-          role-to-assume: arn:aws:iam::751999266872:role/GitHubNet
-          role-session-name: myGitHubActionsNet
+          role-to-assume: ${{ secrets.AWS_ARN_GHA }}
+          role-session-name: GHA-${{ github.run_id }}-${{ matrix.node-version }}-${{ matrix.jdk-version }}-${{ matrix.os }}
 
       - name: Set up JDK ${{ matrix.jdk-version }}
         uses: actions/setup-java@v4
@@ -43,12 +86,12 @@ jobs:
           java-version: ${{ matrix.jdk-version }}
           distribution: 'corretto'
 
-      - name: Set up .NET 6.0.x
+      - name: Set up .NET ${{ matrix.node-version }}
         uses: actions/setup-dotnet@v4
         with:
-          dotnet-version: '6.0.x'
+          dotnet-version: ${{ matrix.node-version }}
 
-      - name: Restore, Build, and Test
+      - name: Build and Test
         run: |
           dotnet build
           dotnet test --no-build
@@ -60,23 +103,67 @@ jobs:
         env:
           AWS_SDK_Version: '4.0.2.1'
 
-      - name: Run KCL Producer
+      # Create unique identifiers for the stream name and application name
+      - name: Set up unique identifiers
         run: |
-          cd SampleProducer
-          dotnet run
+          STREAM_NAME="kclnetsample-${{ matrix.os }}-net${{ matrix.python-version }}-jdk${{ matrix.jdk-version }}"
+          APP_NAME="DotNetKCLSample-${{ matrix.os }}-net${{ matrix.python-version }}-jdk${{ matrix.jdk-version }}"
+          echo "STREAM_NAME=$STREAM_NAME" >> $GITHUB_ENV
+          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
 
-      - name: Run KCL consumer (ubuntu and windows)
-        if: ${{ matrix.os != 'macOS-latest'}}
+      # Manipulate sample.properties file to use unique stream name and application name
+      - name: Manipulate sample.properties file
         run: |
-          cd SampleConsumer
-          timeout 45 dotnet run --project ../Bootstrap/Bootstrap.csproj --properties kcl.properties --execute || status="$?"; if (( status == 124 )); then exit 0; else exit 1; fi; exit "$status"
+          chmod +x .github/scripts/manipulate_properties.sh
+          .github/scripts/manipulate_properties.sh
+        env:
+          RUNNER_OS: ${{ matrix.os }}
+          STREAM_NAME: ${{ env.STREAM_NAME }}
+          APP_NAME: ${{ env.APP_NAME }}
 
-      - name: Run KCL consumer (macOS)
-        if: ${{ matrix.os == 'macOS-latest'}}
+      # Create kinesis stream with unique name and wait for it to exist
+      - name: Create and wait Kinesis stream
         run: |
-          brew install coreutils
-          cd SampleConsumer
-          gtimeout 45 dotnet run --project ../Bootstrap/Bootstrap.csproj --properties kcl.properties --execute || status="$?"; if (( status == 124 )); then exit 0; else exit 1; fi; exit "$status"
+          chmod +x .github/scripts/create_stream.sh
+          .github/scripts/create_stream.sh
+        env:
+          STREAM_NAME: ${{ env.STREAM_NAME }}
+
+      # Put words to sample stream with unique name based on run ID
+      - name: Put words to sample stream
+        run: |
+          chmod +x .github/scripts/put_words_to_stream.sh
+          .github/scripts/put_words_to_stream.sh
+        env:
+          STREAM_NAME: ${{ env.STREAM_NAME }}
+
+#      - name: Run KCL Producer
+#        run: |
+#          cd SampleProducer
+#          dotnet run
+#
+#      - name: Run KCL consumer (ubuntu and windows)
+#        if: ${{ matrix.os != 'macOS-latest'}}
+#        run: |
+#          cd SampleConsumer
+#          timeout 45 dotnet run --project ../Bootstrap/Bootstrap.csproj --properties kcl.properties --execute || status="$?"; if (( status == 124 )); then exit 0; else exit 1; fi; exit "$status"
+#
+#      - name: Run KCL consumer (macOS)
+#        if: ${{ matrix.os == 'macOS-latest'}}
+#        run: |
+#          brew install coreutils
+#          cd SampleConsumer
+#          gtimeout 45 dotnet run --project ../Bootstrap/Bootstrap.csproj --properties kcl.properties --execute || status="$?"; if (( status == 124 )); then exit 0; else exit 1; fi; exit "$status"
+
+      # Clean up all existing Streams and DDB tables
+      - name: Clean up Kinesis Stream and DynamoDB table
+        if: always()
+        run: |
+          chmod +x .github/scripts/clean_up_stream_table.sh
+          .github/scripts/clean_up_stream_table.sh
+        env:
+          STREAM_NAME: ${{ env.STREAM_NAME }}
+          APP_NAME: ${{ env.APP_NAME }}
 
   auto-merge-dependabot:
     needs: [sample-run]
